[package]
name = "bonsai-guest-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
ethabi = { version = "18.0", default-features = false }
risc0-zkvm = { workspace = true, default-features = false }

[dev-dependencies]
hex = "0.4"
