[package]
name = "multisig"
version = "0.12.0"
edition = "2021"

[dependencies]
clap = "4.0"
risc0-zkvm = { path = "../../risc0/zkvm" }
serde = "1.0"
multisig-methods = { path = "methods" }

[dev-dependencies]
hex = "0.4"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
# default = ["metal"]
metal = ["risc0-zkvm/metal"]
