[package]
name = "multisig"
version = "0.1.0"
edition = "2021"

default-run = "multisig"

[dependencies]
multisig-methods = { path = "methods" }
multisig-core = { path = "core" }
k256 = { version = "0.13", features = ["serde"] }
hex = "0.4"
rand_core = "0.6.4"
risc0-zkvm = { path = "../../risc0/zkvm" }
serde = "1.0"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
prove = ["risc0-zkvm/prove"]
