[package]
name = "zk_multisig"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = ["std"] }
sha2 = "0.10.6"
rs_merkle = "1.4.1"
ethabi = { version = "18.0", default-features = false }
hex = "0.4"
k256 = "0.13.1"
sha3 = "0.10.8"
# serde = "1.0"

[patch.crates-io]
# Placing this patch statement in the workspace Cargo.toml will add RISC Zero SHA-256 accelerator
# support for all downstream usages of the `sha2` crate.
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2/v0.10.6-risc0" }

