[package]
name = "afl-fuzzing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0.12.16"
risc0-zkvm = { path = "../../risc0/zkvm/" }