[workspace]

[package]
name = "risc0-zkvm-methods-inner"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "0.10", path = "../..", default-features = false, features = ["std"] }
risc0-zkp = { version = "0.10", path = "../../../../../zkp/rust", default-features = false, features = ["std"] }
simple-c-pkg = { path = "../test-resources/simple-c-pkg", optional = true}

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-zkvm = { version = "0.10", path = "../.." }

[package.metadata.release]
release = false

[[bin]]
name = "cc_default"
required-features = ["risc_cc"]

[[bin]]
name = "cc_release"
required-features = ["risc_cc"]

[features]
default = ["std"]
std = []
test_feature1 = []
test_feature2 = []
risc_cc = ["simple-c-pkg"]
